# Generated by Django 3.0.5 on 2020-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clip',
            field=models.FileField(null=True, upload_to='user_video/'),
        ),
    ]
