# Generated by Django 3.0.5 on 2020-04-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0002_post_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
