# Generated by Django 3.0.5 on 2020-04-20 20:02

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0004_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUpdateView',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='postApp.Post')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.contrib.auth.mixins.UserPassesTestMixin, django.views.generic.edit.UpdateView, 'postApp.post'),
        ),
    ]
