# Generated by Django 3.0.5 on 2020-04-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200416_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='name_default', max_length=500),
        ),
    ]
