# Generated by Django 3.0.5 on 2020-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.FileField(null=True, upload_to='user_video/', verbose_name='IMAGE'),
        ),
    ]
