# Generated by Django 3.0.5 on 2020-04-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
