# Generated by Django 3.0.5 on 2020-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='post_img', max_length=200)),
                ('imagePost', models.ImageField(default='default.jpg', upload_to='post_pics')),
            ],
        ),
    ]
