# Generated by Django 3.0.5 on 2020-04-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_postcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='name',
        ),
        migrations.AddField(
            model_name='postcontent',
            name='post_con',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.Post'),
        ),
    ]
