# Generated by Django 3.0.5 on 2020-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200417_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='imagePost',
            field=models.FileField(default='default.jpg', null=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
