# Generated by Django 3.0.5 on 2020-04-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200418_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
