# Generated by Django 3.0.5 on 2020-04-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200419_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.FileField(null=True, upload_to='user_video/', verbose_name='VID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='tunnel.png', height_field='height_field', null=True, upload_to='post_pic/', width_field='width_field'),
        ),
    ]
