# Generated by Django 3.0.5 on 2020-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200419_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='tunnel.png', height_field='height_field', null=True, upload_to='post_pic/', width_field='width_field'),
        ),
    ]
